### ISSUE TITLE
Cut apk file into pieces, without download the whole file.

### ISSUE THREAD

**Issue by amnyx** [VivekPanyam/Evolve#10]
Considering this scene, i just want to upgrade a part of my app, most function or appearance remains as it was, i just want to upgrade the algorithm of posting users profile picture, for example.
How to do that without downloading the whole package?

**Comment by VivekPanyam** [comment]
If you just want to update some of the logic (i.e. no new activities or services), you could create an apk containing a class with the new logic. Your main app would then dynamically load this class and use it when required.

You probably don't need a lot of the complexity that comes from dynamic activities. Instead of using all of Evolve, it may make sense to just use some of the code for downloading and loading an apk [here](https://github.com/VivekPanyam/EvolveWrapper/blob/master/src/com/vivekpanyam/TestApp/Utils.java) and [here](https://github.com/VivekPanyam/EvolveWrapper/blob/master/src/com/vivekpanyam/TestApp/DynamicApp.java). Good luck!
