### ISSUE TITLE
Custom application support?

### ISSUE THREAD

**Issue by void-main** [VivekPanyam/Evolve#5]
In my application, I have a subclass of Application that does some global setup. I set it up in my app's manifest file. But evolve doesn't seem to give it a chance to run. How can I solve that?

**Comment by VivekPanyam** [comment]
You are correct; Evolve currently does not instantiate an Application subclass.

If you just care about `onCreate`, modify Evolve to call the subclass' `onCreate` [here](https://github.com/VivekPanyam/Evolve/blob/master/src/com/vivekpanyam/evolve/Evolve.java#L155) (at the end of the init method). This is called by the wrapper after it's done loading an APK.

A more robust way to allow Application subclasses is to pass back an `Application` from the main app to the wrapper and proxy all the important methods.
1. Create an Application in your wrapper app (and configure it in the manifest):
   
   ```
   public class EvolveApplication extends Application {
       public static Application dynamicApplication;
   
       @Override
       public void onLowMemory() {
           super.onLowMemory();
           if (dynamicApplication != null) {
               dynamicApplication.onLowMemory();
           }
       }
   
       ...
   }
   ```
2. You can easily pass your `Application` subclass back to the wrapper in `init` [here](https://github.com/VivekPanyam/Evolve/blob/master/src/com/vivekpanyam/evolve/Evolve.java#L155).
3. You will then need to retrieve this `Application` in EvolveWrapper [here](https://github.com/VivekPanyam/EvolveWrapper/blob/master/src/com/vivekpanyam/TestApp/DynamicApp.java#L106) and set `EvolveApplication.dynamicApplication`

**Note: You will still need to manually call onCreate on your subclass because `EvolveApplication.onCreate` will be called before `EvolveApplication.dynamicApplication` is set.**

Hopefully that's helpful. It would be great if you could submit a pull request to implement this!

**Comment by void-main** [comment]
@VivekPanyam thank you for your detailed explanation. Currently I'm looking for a neat way to make it easy for developers to hot-fix some bugs without publishing and waiting for the user to install new apps. That's why I found your repo. I'm on early stage of my research, and I'm happy to contribute to this repo when we decided to use this method. Great job!

**Comment by void-main** [comment]
@VivekPanyam One more question, you said `You can easily pass your Application subclass back to the wrapper in init here.` But I really can't. In the init method, the context is the wrapper application, not the dynamic one. The best I can do is to create a new instance of my dynamic application, and pass it back. But the created instance is not a prepared one, by that I mean, if I call `onCreate` manually, the `getApplicationContext()` method gives me `null` inside `onCreate` method.

Here's a piece of code that I used to create a new instance:

```
    try {
            Class<Application> appClass = (Class<Application>) Class.forName("MY_APPLICATION_SUBCLASS_NAME", true, Evolve.classLoader);
            app = appClass.getConstructor().newInstance();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        }
```

**Comment by VivekPanyam** [comment]
One way to solve this problem is to create a `DynamicApplication` class in Evolve that extends `Application` and override `getApplicationContext` to return `Evolve.context`. If you do this, it's probably wise to rename `DynamicApp` in EvolveWrapper to avoid confusion.

Does that make sense?

**Comment by hasanmumin** [comment]
Hi,
So only i need this;

```
public class EvolveApplication extends Application {

    @Override
    public Context getApplicationContext() {
        return Evolve.context;
    }
}
```

right ? or i need do something else ?
