### ISSUE TITLE
Extending PreferenceActivity

### ISSUE THREAD

**Issue by ravanova** [VivekPanyam/Evolve#8]
In the Evolve read-me it states that all Activity's in the loaded apk should extend DynamicActivity. How do we achieve this for PreferenceActivity?

**Comment by VivekPanyam** [comment]
I think it would be quite similar to [DynamicListActivity](https://github.com/VivekPanyam/Evolve/blob/master/src/com/vivekpanyam/evolve/DynamicListActivity.java). Create a DynamicPreferenceActivity that extends PreferenceActivity and overrides the appropriate methods (see DynamicListActivity). You would then extend DynamicPreferenceActivity instead of extending PreferenceActivity. Does that help?
